const KEY="healthtracker.v1";let db=JSON.parse(localStorage.getItem(KEY)||"[]");const $=s=>document.querySelector(s);const now=()=>new Date().toISOString();const forms={
daily:{title:"Daily check-in",fields:[["sleep_hours","Sleep (hours)","number","0.1"],["sleep_quality","Sleep quality (1–5)","number","1"],["energy","Energy (1–5)","number","1"],["notes","Notes (optional)","text"]]},
measurement:{title:"Weight & waist",fields:[["weight_lb","Weight (lb)","number","0.1"],["waist_in","Waist (in, optional)","number","0.1"]]},
bp:{title:"Blood pressure",fields:[["systolic","Systolic","number","1"],["diastolic","Diastolic","number","1"],["pulse","Pulse (bpm)","number","1"]]},
workout:{title:"Workout",fields:[["workout_type","Workout type","select",["BJJ","Strength","Cardio","Walking / Hiking","Mobility","Other"]],["duration_min","Duration (minutes)","number","1"],["intensity","Intensity","select",["Easy","Moderate","Hard","Very Hard"]],["notes","Notes (optional)","text"]]}
};let active;
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function fieldHTML(f){let[n,l,t,x]=f;if(t==="select")return '<div class="field"><label>'+l+'</label><select name="'+n+'" required>'+x.map(v=>'<option>'+v+'</option>').join("")+'</select></div>';return '<div class="field"><label>'+l+'</label><input name="'+n+'" type="'+t+'" '+(x?'step="'+x+'"':'')+' '+(l.includes("optional")?'':'required')+'></div>'}
document.querySelectorAll("[data-form]").forEach(b=>b.onclick=()=>{active=b.dataset.form;let f=forms[active];$("#formTitle").textContent=f.title;$("#fields").innerHTML=f.fields.map(fieldHTML).join("");$("#modal").showModal()});
$("#close").onclick=()=>$("#modal").close();
$("#entryForm").onsubmit=e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target).entries());db.push({id:crypto.randomUUID(),type:active,datetime:now(),...data});save();$("#modal").close();e.target.reset();$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1300)};
function summary(x){if(x.type==="measurement")return (x.weight_lb?x.weight_lb+" lb":"")+(x.waist_in?" • "+x.waist_in+' in':"");if(x.type==="bp")return x.systolic+"/"+x.diastolic+" • "+x.pulse+" bpm";if(x.type==="workout")return x.workout_type+" • "+x.duration_min+" min • "+x.intensity;if(x.type==="daily")return x.sleep_hours+"h sleep • energy "+x.energy+"/5"}
function render(){$("#recent").innerHTML=db.slice().reverse().slice(0,8).map(x=>'<div class="row"><div><b>'+forms[x.type].title+'</b><br><span>'+summary(x)+'</span></div><span>'+new Date(x.datetime).toLocaleDateString(undefined,{month:"short",day:"numeric"})+'</span></div>').join("")||'<div class="row"><span>No entries yet. Your first log will appear here.</span></div>'}
$("#clear").onclick=()=>{if(db.length&&confirm("Delete all locally stored HealthTracker entries?")){db=[];save()}};
function csvEscape(v){v=v??"";v=String(v);return /[",\n]/.test(v)?'"'+v.replaceAll('"','""')+'"':v}
$("#backup").onclick=async()=>{const cols=["datetime","type","sleep_hours","sleep_quality","energy","weight_lb","waist_in","systolic","diastolic","pulse","workout_type","duration_min","intensity","notes"];const csv=[cols.join(","),...db.map(x=>cols.map(c=>csvEscape(x[c])).join(","))].join("\n");const blob=new Blob([csv],{type:"text/csv"});const file=new File([blob],"healthtracker_backup.csv",{type:"text/csv"});if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share({files:[file]});return}catch(e){if(e.name==="AbortError")return}}const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="healthtracker_backup.csv";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$("#today").textContent=new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");